### ISSUE TITLE
InfiniteScroll component keeps calling loadMore function until hasMore is false?

### ISSUE THREAD

**Issue by hezjing** [guillaumervls/react-infinite-scroll#18]
Hi

When my page is rendered and without any user interaction, the `InfiniteScroll` component keeps calling the `loadMore` function until the `hasMore` is set to false. I'm expecting that the component will call the `loadMore` function when the user moves the scroll bar.

Any idea what am I missing here?

**Comment by egdelwonk** [comment]
I'm running into the same thing. Any insight ?

**Comment by t-d-d** [comment]
I had the same or similar problem but have got it working.  It was caused by my use of floating divs in {items}.  I changed my layout but you could probably use one of the methods here http://www.sitepoint.com/simple-clearing-of-floats/ .  And maybe an option could be added to the component to clear floats?

Could another cause of this be when you have images loading in {items} without their dimensions being explicitly being set?

**Comment by OfekA** [comment]
Running into the same issue, im using http://material-ui.com/ as my components.
