### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by tom-james-watson** [guillaumervls/react-infinite-scroll#25]
The jsfiddle doesn't seem to work at the moment?

**Comment by hekar** [comment]
Same here. I do not see any errors in the developer console when I run the demo, but nothing shows up.

Found another demo here: http://codepen.io/dazld/pen/cdbgj

**Comment by thomasyates** [comment]
The problem is the external resources used in the jsfiddle,namely react-with-addons-0.5.1.js, which I presume is no longer available from the original location.

"Failed to load resource: the server responded with a status of 400 (Bad Request)
http://dragon.ak.fbcdn.net/hphotos-ak-prn1/851568_213431688839622_33425_n.js"

Good find @hekar (the codepen).
