### ISSUE TITLE
Uncaught TypeError: this.getDOMNode is not a function

### ISSUE THREAD

**Issue by ItsMrAkhil** [guillaumervls/react-infinite-scroll#39]
When scrolling I'm getting an Uncaught TypeError: this.getDOMNode is not a function in below function

```
scrollListener: function () {
          var el = this.getDOMNode();
          var scrollTop = (window.pageYOffset !== undefined) ? window.pageYOffset : (document.documentElement || document.body.parentNode || document.body).scrollTop;
          if (topPosition(el) + el.offsetHeight - scrollTop - window.innerHeight < Number(this.props.threshold)) {
            this.detachScrollListener();
            // call loadMore after detachScrollListener to allow
            // for non-async loadMore functions
            this.props.loadMore(this.pageLoaded += 1);
          }
```

**Comment by danbovey** [comment]
This package is no longer being maintained, so if you're using a newer version of React, like 15.x you need to be using the fork I'm running at https://github.com/CassetteRocks/react-infinite-scroller.

You're getting this error because the function for `getDOMNode` has been moved/renamed in the newer ReactDOM API.

**Comment by akhilpab** [comment]
Thanks for the reply. I'm started using your fork. It is working fine thank you.
@danbovey
